trigger:
- master

stages:
- stage: "BuildStage"
  jobs:
  - job: "BuildJob"
    pool:
    #   name: myagent
    #   demands: 
    #   - agent.name -equals dotnet
      vmImage: ubuntu-latest

    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: "DeployToDev"
  dependsOn: "BuildStage"
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest

    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'DSS Training7 service connection'
        appType: 'webApp'
        WebAppName: 'hwa-dev'
        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

- stage: "DeployToQA"
  dependsOn: "DeployToDev"
  jobs:
  - job:
    pool:
    #  name: ubuntu-latest
    #  demands:
    #  - agent.name -equals dotnet
      vmImage: ubuntu-latest

    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'DSS Training7 service connection'
        appType: 'webApp'
        WebAppName: 'hwa-qa'
        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
    
- stage: "DeployToProduction"
  dependsOn: "DeployToQA"
  jobs:
  - job:
    pool:
    #  name: ubuntu-latest
    #  demands:
    #  - agent.name -equals dotnet
       vmImage: ubuntu-latest

    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'DSS Training7 service connection'
        appType: 'webApp'
        WebAppName: 'hwa-prod'
        deployToSlotOrASE: true
        ResourceGroupName: 'helloworldapp'
        SlotName: 'staging'
        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

    