trigger:
- master

pool:
 name: myagent
 demands: 
  - agent.name -equals dotnet

steps:
- template: 'templates/restoreandbuild.yml'
  parameters:
    buildConfiguration: 'Debug'

- template: 'templates/restoreandbuild.yml'
  parameters:
    buildConfiguration: 'Release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'