trigger:
- none

pool:
 vmImage: windows-latest

stages:
- stage: "BuildStage"
  jobs:
  - job: "BuildJob"
    steps:
      - task: DotNetCoreCLI@2
        displayName: "DotnetRestore"
        inputs:
          command: 'restore'
          projects: '**/HelloWorldApp.Web.csproj'
          feedsToUse: 'select'
      
      - task: DotNetCoreCLI@2
        displayName: "DotnetBuild"
        inputs:
          command: 'build'
          projects: '**/HelloWorldApp.Web.csproj'
          arguments: '-c $(BuildConfiguration)'

      
      - task: DotNetCoreCLI@2
        displayName: "DotnetPublish"
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '-c $(BuildConfiguration) -o $(Pipeline.Workspace)'
      
      - task: PublishPipelineArtifact@1
        displayName: "Publishing Pipeline Artifacts"
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'drop'
          publishLocation: 'pipeline'