trigger:
- master
- dev
- feature

pool:
 vmImage: ubuntu-latest

stages:
- stage: "BuildStage"
  jobs:
  - job: "BuildJob"
    steps:
    - task: DotNetCoreCLI@2
      displayName: "restore"
      inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: "build"
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    # - task: DotNetCoreCLI@2
    #   displayName: "test"
    #   inputs:
    #     command: 'test'
    #     projects: '**/*Tests.csproj'
    #     arguments: '--no-build --configuration $(buildConfiguration)'
    #     publishTestResults: true
    - task: DotNetCoreCLI@2
      displayName: "publish"
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: "DeployToDev"
  dependsOn: "BuildStage"
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
  jobs:
  - deployment: 
    pool:
      vmImage: ubuntu-latest
    environment: "Development"
    strategy:
     runOnce:
       deploy:
        steps:
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'DSS7'
            appType: 'webApp'
            WebAppName: 'hwaa-dev'
            packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

- stage: "DeployToQa"
  dependsOn: "DeployToDev"
  jobs:
  - deployment: 
    pool:
      vmImage: ubuntu-latest
    environment: "QA"
    strategy:
     runOnce:
       deploy:
        steps:
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'DSS7'
            appType: 'webApp'
            WebAppName: 'hwaa-qa'
            packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

- stage: "DeployToProd"
  dependsOn: "BuildStage"
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - deployment: 
    pool:
      vmImage: ubuntu-latest
    environment: "Production"
    strategy:
     runOnce:
       deploy:
        steps:
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'DSS7'
            appType: 'webApp'
            WebAppName: 'hwaa-prod'
            deployToSlotOrASE: true
            ResourceGroupName: 'helloworldapp'
            SlotName: 'staging'
            packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
        - task: AzureAppServiceManage@0
          inputs:
            azureSubscription: 'DSS7'
            Action: 'Swap Slots'
            WebAppName: 'hwaa-prod'
            ResourceGroupName: 'helloworldapp'
            SourceSlot: 'staging'
  
       