trigger:
- master

stages:
- stage: "BuildStage"
  jobs:
  - job: "BuildJob"
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'      
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: "DeployToDev"
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'DSS'
        appType: 'webApp'
        WebAppName: 'hwa-dev'
        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

- stage: "DeployToQA"
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'DSS'
        appType: 'webApp'
        WebAppName: 'hwa-qa'
        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

- stage: "DeployToProd"
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'DSS'
        appType: 'webApp'
        WebAppName: 'hwa-prod'
        deployToSlotOrASE: true
        ResourceGroupName: 'helloworldapp'
        SlotName: 'staging'
        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'    
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'DSS'
        Action: 'Swap Slots'
        WebAppName: 'hwa-prod'
        ResourceGroupName: 'helloworldapp'
        SourceSlot: 'staging'