trigger:
- master

pool:
 vmImage: ubuntu-latest

stages:
- stage: "BuildStage"
  jobs:
  - job: "BuildJob"
    steps:
    - task: DotNetCoreCLI@2
      displayName: "restore"
      inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: "build"
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: "publish"
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: "DeployToDev"
  dependsOn: