trigger:
- master

pool:
 vmImage: ubuntu-latest

stages:
- stage: "BuildStage"
  jobs:
  - job: "BuildJob"
    steps:
    - task: DotNetCoreCLI@2
      displayName: "Dotnet Restore"
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: "Dotnet Build"
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: "Dotnet publish"
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--output $(build.ArtifactStagingDirectory) --configuration $(buildConfiguration)'  
    - task: PublishPipelineArtifact@1
      inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'drop'
          publishLocation: 'pipeline'

- stage: "DeploytoDev"
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'DSS'
        appType: 'webApp'
        WebAppName: 'hwa-dev'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- stage: "DeploytoQA"
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'DSS'
        appType: 'webApp'
        WebAppName: 'hwa-qa'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- stage: "DeploytoProd"
  jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'DSS'
        appType: 'webApp'
        WebAppName: 'hwa-prod'
        deployToSlotOrASE: true
        ResourceGroupName: 'helloworldapp'
        SlotName: 'staging'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'DSS'
        Action: 'Swap Slots'
        WebAppName: 'hwa-prod'
        ResourceGroupName: 'helloworldapp'
        SourceSlot: 'staging'